model: 'mban'
## parameters for plain
scale: 4
rgb_range: 255
colors: 3
m_elan: 6  #12
c_elan: 54  #54
n_share: 0
r_expand: 2
act_type: 'relu'
window_sizes: [4, 8, 16]   ##[4,8,16]
pretrain:

## parameters for model training
patch_size: 192   # 256
batch_size: 16
data_repeat: 10   # 10  80
data_augment: 1

epochs: 500     # 1000
lr: 0.0005
decays: [200, 400, 600, 800, 900]    ## [200, 330, 420, 470, 490]      # [200, 400, 600, 800, 900]    #
gamma: 0.5
log_every: 100
test_every: 1
log_path: ".\\experiments"
log_name:

## hardware specification
gpu_ids: [1]
threads: 1   # 8

## data specification
data_path: 'D:\\yyj\\proC\\dataset'
eval_sets: ['Set5', 'Set14', 'B100', 'Urban100']
# eval_sets: ['Set5', 'Set14', 'B100', 'Urban100', 'Manga109']